Reina.Cryptography: Reina.Cryptography.KeyManagement.AzureKVKeyManager Class Reference
Reina.Cryptography.KeyManagement.AzureKVKeyManager Class Reference
Manages 256-bit cryptographic keys by interfacing with Azure Key Vault, providing secure storage and retrieval of keys. This class implements a caching mechanism to optimize key retrieval performance by reducing the number of round trips to the key vault.
Public Member Functions
AzureKVKeyManager (string vaultUri, string clientId, string clientSecret, string tenantId)
Initializes a new instance of the AzureKVKeyManager class.
async Task< byte[]> GetEncryptionKeyAsync (string baseKeyName)
Asynchronously retrieves an encryption key from Azure Key Vault or the local cache.
async Task< List< byte[]> > GetDecryptionKeysAsync (string baseKeyName)
Asynchronously retrieves an encryption key from Azure Key Vault or the local cache.
Properties
static AzureKVKeyManager Instance [get]
Gets the singleton instance of the AzureKVKeyManager.
Private Member Functions
async Task<(string versionedName, byte[] key)> EnsureRotatedKeyAsync (string baseKeyName)
Ensures that a cryptographic key is present and rotated if necessary based on the configured threshold. If no key exists, it creates the initial version. If the latest version is older than the rotation threshold, it creates a new version. Also cleans up versions older than the configured retention period.
byte[] Generate256bitKey ()
Generates a new 256-bit cryptographic key.
Private Attributes
readonly SecretClient _secretClient
Static Private Attributes
static readonly ConcurrentDictionary< string, byte[]> _keyCache = new()
static readonly Lazy< AzureKVKeyManager > _instance
Detailed Description
Manages 256-bit cryptographic keys by interfacing with Azure Key Vault, providing secure storage and retrieval of keys. This class implements a caching mechanism to optimize key retrieval performance by reducing the number of round trips to the key vault.
Definition at line 18 of file AzureKVKeyManager.cs.
Constructor & Destructor Documentation
AzureKVKeyManager()
Reina.Cryptography.KeyManagement.AzureKVKeyManager.AzureKVKeyManager (string vaultUri, string clientId, string clientSecret, string tenantId) inline
Initializes a new instance of the AzureKVKeyManager class.
Parameters
vaultUri The URI of the Azure Key Vault.
clientId The client ID for Azure Active Directory authentication.
clientSecret The client secret for Azure Active Directory authentication.
tenantId The tenant ID for Azure Active Directory authentication.
Definition at line 47 of file AzureKVKeyManager.cs.
        {
            var clientOptions = new SecretClientOptions
            {
                Retry =
                {
                    Delay = TimeSpan.FromSeconds(1),
                    MaxDelay = TimeSpan.FromSeconds(10),
                    MaxRetries = 5,
                    Mode = RetryMode.Exponential
                }
            };
            var credential = new ClientSecretCredential(tenantId, clientId, clientSecret);
            _secretClient = new SecretClient(new Uri(vaultUri), credential, clientOptions);
        }
References Reina.Cryptography.KeyManagement.AzureKVKeyManager._secretClient.
Member Function Documentation
EnsureRotatedKeyAsync()
async Task<(string versionedName, byte[] key)> Reina.Cryptography.KeyManagement.AzureKVKeyManager.EnsureRotatedKeyAsync (string baseKeyName) inline private
Ensures that a cryptographic key is present and rotated if necessary based on the configured threshold. If no key exists, it creates the initial version. If the latest version is older than the rotation threshold, it creates a new version. Also cleans up versions older than the configured retention period.
Parameters
baseKeyName The base name of the key (without version suffix).
Returns
A tuple containing the versioned key name and the associated 256-bit key as a byte array.
Exceptions
UnauthorizedAccessException Thrown when authentication or authorization with Azure Key Vault fails.
Exception Thrown when an error occurs during the retrieval, creation, or rotation of secrets.
Definition at line 191 of file AzureKVKeyManager.cs.
        {
            try
            {
                var cfg = Config.Instance;
                var versionPattern = new Regex($"^{Regex.Escape(baseKeyName)}--v(\\d+)$", RegexOptions.Compiled);
                var versions = new List<(int, SecretProperties)>();
                await foreach (var prop in _secretClient.GetPropertiesOfSecretsAsync())
                {
                    var match = versionPattern.Match(prop.Name);
                    if (match.Success && int.TryParse(match.Groups[1].Value, out int version))
                        versions.Add((version, prop));
                }
                if (versions.Count == 0)
                {
                    string name = $"{baseKeyName}--v1";
                    byte[] key = Generate256bitKey();
                    await _secretClient.SetSecretAsync(name, Convert.ToBase64String(key)).ConfigureAwait(false);
                    return (name, key);
                }
                var sorted = versions.OrderByDescending(v => v.Item1).ToList();
                var (latestVersion, latestProp) = sorted.First();
                var created = latestProp.CreatedOn ?? DateTimeOffset.UtcNow;
                if (created.Add(cfg.KeyRotationThreshold) <= DateTimeOffset.UtcNow)
                {
                    int newVersion = latestVersion + 1;
                    string name = $"{baseKeyName}--v{newVersion}";
                    byte[] key = Generate256bitKey();
                    await _secretClient.SetSecretAsync(name, Convert.ToBase64String(key)).ConfigureAwait(false);
                    var cutoff = DateTimeOffset.UtcNow.Subtract(cfg.KeyRetentionPeriod);
                    foreach (var (_, prop) in sorted)
                    {
                        if ((prop.CreatedOn ?? DateTimeOffset.UtcNow) < cutoff)
                            try { await _secretClient.StartDeleteSecretAsync(prop.Name).ConfigureAwait(false); } catch { }
                    }
                    return (name, key);
                }
                else
                {
                    var secret = await _secretClient.GetSecretAsync(latestProp.Name);
                    return (latestProp.Name, Convert.FromBase64String(secret.Value.Value));
                }
            }
            catch (Azure.RequestFailedException ex) when (ex.Status == 401)
            {
                throw new UnauthorizedAccessException("Failed to authenticate with Azure Key Vault. Check credentials.", ex);
            }
            catch (Azure.RequestFailedException ex) when (ex.Status == 403)
            {
                throw new UnauthorizedAccessException("Access denied. Check Key Vault permissions.", ex);
            }
            catch (Azure.RequestFailedException ex)
            {
                throw new Exception($"Azure Key Vault error: {ex.Message}", ex);
            }
            catch (Exception ex)
            {
                throw new Exception($"Unexpected error in EnsureRotatedKeyAsync: {ex.Message}", ex);
            }
        }
References Reina.Cryptography.KeyManagement.AzureKVKeyManager._secretClient, Reina.Cryptography.KeyManagement.AzureKVKeyManager.Generate256bitKey(), and Reina.Cryptography.Configuration.Config.Instance.
Referenced by Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetDecryptionKeysAsync(), and Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetEncryptionKeyAsync().
Generate256bitKey()
byte[] Reina.Cryptography.KeyManagement.AzureKVKeyManager.Generate256bitKey () inline private
Generates a new 256-bit cryptographic key.
Returns
A byte array containing the generated key.
Definition at line 262 of file AzureKVKeyManager.cs.
        {
            using var aesAlg = Aes.Create();
            aesAlg.KeySize = 256;
            aesAlg.GenerateKey();
            return aesAlg.Key;
        }
Referenced by Reina.Cryptography.KeyManagement.AzureKVKeyManager.EnsureRotatedKeyAsync().
GetDecryptionKeysAsync()
async Task< List< byte[]> > Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetDecryptionKeysAsync (string baseKeyName) inline
Asynchronously retrieves an encryption key from Azure Key Vault or the local cache.
Parameters
baseKeyName The base name of the key to retrieve (without version suffix).
Returns
A byte array containing the encryption key.
Exceptions
UnauthorizedAccessException Thrown when authentication or authorization with Azure Key Vault fails.
Exception Thrown when an unexpected error occurs during key retrieval or generation.
Definition at line 108 of file AzureKVKeyManager.cs.
        {
            var cfg = Config.Instance;
            var versionPattern = new Regex($"^{Regex.Escape(baseKeyName)}--v(\\d+)$", RegexOptions.Compiled);
            var versions = new List<(int Version, SecretProperties Props)>();
            try
            {
                await foreach (var prop in _secretClient.GetPropertiesOfSecretsAsync().ConfigureAwait(false))
                {
                    var match = versionPattern.Match(prop.Name);
                    if (match.Success && int.TryParse(match.Groups[1].Value, out int version))
                        versions.Add((version, prop));
                }
                if (versions.Count == 0)
                {
                    var freshKey = await GetEncryptionKeyAsync(baseKeyName).ConfigureAwait(false);
                    return new List<byte[]> { freshKey };
                }
                var sorted = versions.OrderByDescending(v => v.Version).ToList();
                var keys = new List<byte[]>();
                foreach (var (v, prop) in sorted)
                {
                    if (_keyCache.TryGetValue(prop.Name, out var cached))
                    {
                        keys.Add(cached);
                        continue;
                    }
                    try
                    {
                        var secret = (await _secretClient.GetSecretAsync(prop.Name).ConfigureAwait(false)).Value;
                        var key = Convert.FromBase64String(secret.Value);
                        _keyCache[prop.Name] = key;
                        keys.Add(key);
                    }
                    catch
                    {
                        // Ignore and skip missing/invalid secrets
                    }
                }
                // Ensure rotation during decryption flow
                await EnsureRotatedKeyAsync(baseKeyName).ConfigureAwait(false);
                return keys;
            }
            catch (Azure.RequestFailedException ex) when (ex.Status == 401)
            {
                throw new UnauthorizedAccessException("Failed to authenticate with Azure Key Vault. Please check your credentials.", ex);
            }
            catch (Azure.RequestFailedException ex) when (ex.Status == 403)
            {
                throw new UnauthorizedAccessException("Access denied. The application does not have the necessary permissions to access the Azure Key Vault secret.", ex);
            }
            catch (Azure.RequestFailedException ex)
            {
                throw new Exception($"An error occurred while accessing Azure Key Vault: {ex.Message}", ex);
            }
            catch (Exception ex)
            {
                throw new Exception($"An unexpected error occurred: {ex.Message}", ex);
            }
        }
References Reina.Cryptography.KeyManagement.AzureKVKeyManager._keyCache, Reina.Cryptography.KeyManagement.AzureKVKeyManager._secretClient, Reina.Cryptography.KeyManagement.AzureKVKeyManager.EnsureRotatedKeyAsync(), Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetEncryptionKeyAsync(), and Reina.Cryptography.Configuration.Config.Instance.
Referenced by Reina.Cryptography.Library.Decrypt().
GetEncryptionKeyAsync()
async Task< byte[]> Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetEncryptionKeyAsync (string baseKeyName) inline
Asynchronously retrieves an encryption key from Azure Key Vault or the local cache.
Parameters
baseKeyName The name of the key to retrieve.
Returns
A byte array containing the encryption key.
Exceptions
UnauthorizedAccessException Thrown when authentication or authorization with Azure Key Vault fails.
Exception Thrown when an unexpected error occurs during key retrieval or generation.
Implements Reina.Cryptography.Interfaces.IKeyManager.
Definition at line 71 of file AzureKVKeyManager.cs.
        {
            try
            {
                if (_keyCache.TryGetValue(baseKeyName, out var cachedKey))
                    return cachedKey;
                var (versionedName, key) = await EnsureRotatedKeyAsync(baseKeyName).ConfigureAwait(false);
                _keyCache[baseKeyName] = key;
                return key;
            }
            catch (Azure.RequestFailedException ex) when (ex.Status == 401)
            {
                throw new UnauthorizedAccessException("Failed to authenticate with Azure Key Vault. Check credentials.", ex);
            }
            catch (Azure.RequestFailedException ex) when (ex.Status == 403)
            {
                throw new UnauthorizedAccessException("Access denied. Check Key Vault permissions.", ex);
            }
            catch (Azure.RequestFailedException ex)
            {
                throw new Exception($"Azure Key Vault error: {ex.Message}", ex);
            }
            catch (Exception ex)
            {
                throw new Exception($"Unexpected error in GetEncryptionKeyAsync: {ex.Message}", ex);
            }
        }
References Reina.Cryptography.KeyManagement.AzureKVKeyManager._keyCache, and Reina.Cryptography.KeyManagement.AzureKVKeyManager.EnsureRotatedKeyAsync().
Referenced by Reina.Cryptography.Library.Encrypt(), and Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetDecryptionKeysAsync().
Member Data Documentation
_instance
readonly Lazy<AzureKVKeyManager> Reina.Cryptography.KeyManagement.AzureKVKeyManager._instance static private
Initial value:
= new(() =>
        {
            Config.Instance.ValidateConfiguration();
            return new AzureKVKeyManager(
                Config.Instance.AzureKeyVaultUrl,
                Config.Instance.AzureClientId,
                Config.Instance.AzureClientSecret,
                Config.Instance.AzureTenantId
            );
        })
Definition at line 24 of file AzureKVKeyManager.cs.
_keyCache
readonly ConcurrentDictionary<string, byte[]> Reina.Cryptography.KeyManagement.AzureKVKeyManager._keyCache = new() static private
Definition at line 21 of file AzureKVKeyManager.cs.
Referenced by Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetDecryptionKeysAsync(), and Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetEncryptionKeyAsync().
_secretClient
readonly SecretClient Reina.Cryptography.KeyManagement.AzureKVKeyManager._secretClient private
Definition at line 20 of file AzureKVKeyManager.cs.
Referenced by Reina.Cryptography.KeyManagement.AzureKVKeyManager.AzureKVKeyManager(), Reina.Cryptography.KeyManagement.AzureKVKeyManager.EnsureRotatedKeyAsync(), and Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetDecryptionKeysAsync().
Property Documentation
Instance
AzureKVKeyManager Reina.Cryptography.KeyManagement.AzureKVKeyManager.Instance static get
Gets the singleton instance of the AzureKVKeyManager.
Definition at line 38 of file AzureKVKeyManager.cs.
Referenced by Reina.Cryptography.Library.Decrypt(), and Reina.Cryptography.Library.Encrypt().
The documentation for this class was generated from the following file:
KeyManagement/AzureKVKeyManager.cs