Reina.Cryptography: Reina.Cryptography.Decryption.DataDecryptor Class Reference
Reina.Cryptography.Decryption.DataDecryptor Class Reference
Implements decryption operations using a cascading triple-layered technique with Twofish, Serpent, and AES algorithms. This class provides a high level of security by decrypting data in multiple stages.
Public Member Functions
DataDecryptor (byte[] twofishKey, byte[] serpentKey, byte[] aesKey)
Initializes a new instance of the DataDecryptor class with the specified keys for Twofish, Serpent, and AES.
byte[] Decrypt (byte[] encryptedBytes)
Decrypts the specified encrypted data using a layered approach with AES, Serpent, and Twofish algorithms.
Private Member Functions
void ValidateKey (byte[] key, string whichKey)
Validates the length of the provided cryptographic key.
byte[] DecryptWithAES (byte[] encryptedBytes)
Decrypts the data using the AES algorithm in CBC mode with PKCS7 padding.
byte[] DecryptWithSerpent (byte[] encryptedBytes)
Decrypts the data using the Serpent algorithm in CBC mode with PKCS7 padding.
byte[] DecryptWithTwofish (byte[] encryptedBytes)
Decrypts the data using the Twofish algorithm in CBC mode with PKCS7 padding.
byte[] ProcessCipher (IBufferedCipher cipher, byte[] input)
Processes the cipher operation (decryption) on the given input data.
Private Attributes
readonly byte[] _twofishKey
readonly byte[] _serpentKey
readonly byte[] _aesKey
Detailed Description
Implements decryption operations using a cascading triple-layered technique with Twofish, Serpent, and AES algorithms. This class provides a high level of security by decrypting data in multiple stages.
Definition at line 18 of file DataDecryptor.cs.
Constructor & Destructor Documentation
DataDecryptor()
Reina.Cryptography.Decryption.DataDecryptor.DataDecryptor (byte[] twofishKey, byte[] serpentKey, byte[] aesKey) inline
Initializes a new instance of the DataDecryptor class with the specified keys for Twofish, Serpent, and AES.
Parameters
twofishKey The 256-bit Twofish key for decryption.
serpentKey The 256-bit Serpent key for decryption.
aesKey The 256-bit AES key for decryption.
Exceptions
ArgumentNullException Thrown when any key is null.
ArgumentException Thrown when any key is not 256 bits in length.
Definition at line 32 of file DataDecryptor.cs.
         {
             _twofishKey = twofishKey ?? throw new ArgumentNullException(nameof(twofishKey), "Twofish key cannot be null.");
             _serpentKey = serpentKey ?? throw new ArgumentNullException(nameof(serpentKey), "Serpent key cannot be null.");
             _aesKey = aesKey ?? throw new ArgumentNullException(nameof(aesKey), "AES key cannot be null.");
             ValidateKey(_twofishKey, nameof(twofishKey));
             ValidateKey(_serpentKey, nameof(serpentKey));
             ValidateKey(_aesKey, nameof(aesKey));
         }
References Reina.Cryptography.Decryption.DataDecryptor._aesKey, Reina.Cryptography.Decryption.DataDecryptor._serpentKey, Reina.Cryptography.Decryption.DataDecryptor._twofishKey, and Reina.Cryptography.Decryption.DataDecryptor.ValidateKey().
Member Function Documentation
Decrypt()
byte [] Reina.Cryptography.Decryption.DataDecryptor.Decrypt (byte[] encryptedBytes) inline
Decrypts the specified encrypted data using a layered approach with AES, Serpent, and Twofish algorithms.
Parameters
encryptedBytes The encrypted data to decrypt.
Returns
The decrypted data as a byte array.
Exceptions
ArgumentNullException Thrown when the encrypted data is null.
CryptographicException Thrown when decryption fails due to invalid padding or other cryptographic issues.
ArgumentException Thrown when the encrypted data is too short or corrupted.
Implements Reina.Cryptography.Interfaces.IDecryptor.
Definition at line 63 of file DataDecryptor.cs.
         {
             if (encryptedBytes == null)
                 throw new ArgumentNullException(nameof(encryptedBytes), "Encrypted data cannot be null.");
             // Attempt to decrypt the data in a try-catch block to handle potential cryptographic exceptions.
             try
             {
                 // Perform decryption in reverse order of encryption: first AES, then Serpent, and finally Twofish.
                 byte[] aesDecrypted = DecryptWithAES(encryptedBytes);
                 byte[] serpentDecrypted = DecryptWithSerpent(aesDecrypted);
                 byte[] twofishDecrypted = DecryptWithTwofish(serpentDecrypted);
                 return twofishDecrypted;
             }
             catch (CryptographicException ce)
             {
                 // Provide more context to the cryptographic exception for better error diagnosis.
                 throw new CryptographicException("Decryption failed: " + ce.Message, ce);
             }
             catch (ArgumentException ae)
             {
                 // Re-throw the argument exception with additional context.
                 throw new ArgumentException("Decryption failed: " + ae.Message, ae);
             }
             catch (Exception ex)
             {
                 // General exception handling as a fallback to catch any other unexpected errors.
                 throw new Exception("Decryption failed: An unexpected error occurred.", ex);
             }
         }
References Reina.Cryptography.Decryption.DataDecryptor.DecryptWithAES(), Reina.Cryptography.Decryption.DataDecryptor.DecryptWithSerpent(), and Reina.Cryptography.Decryption.DataDecryptor.DecryptWithTwofish().
DecryptWithAES()
byte [] Reina.Cryptography.Decryption.DataDecryptor.DecryptWithAES (byte[] encryptedBytes) inline private
Decrypts the data using the AES algorithm in CBC mode with PKCS7 padding.
Parameters
encryptedBytes The encrypted data with the AES IV prepended.
Returns
The decrypted data as a byte array.
Exceptions
ArgumentException Thrown when the encrypted data does not contain a valid AES IV.
Definition at line 101 of file DataDecryptor.cs.
         {
             using var aes = Aes.Create();
             {
                 int ivLengthAes = aes.BlockSize / 8;
                 if (encryptedBytes.Length < ivLengthAes)
                     throw new ArgumentException("The encrypted data is too short to contain the AES IV.", nameof(encryptedBytes));
                 // Extract the IV from the beginning of the encrypted data.
                 var ivAes = new byte[ivLengthAes];
                 Array.Copy(encryptedBytes, ivAes, ivLengthAes);
                 aes.Key = _aesKey;
                 aes.IV = ivAes;
                 // Decrypt the remaining encrypted data after the IV.
                 using var memoryStream = new MemoryStream(encryptedBytes, ivLengthAes, encryptedBytes.Length - ivLengthAes);
                 using var cryptoStream = new CryptoStream(memoryStream, aes.CreateDecryptor(), CryptoStreamMode.Read);
                 using var streamReader = new MemoryStream();
                 cryptoStream.CopyTo(streamReader);
                 return streamReader.ToArray();
             }
         }
References Reina.Cryptography.Decryption.DataDecryptor._aesKey.
Referenced by Reina.Cryptography.Decryption.DataDecryptor.Decrypt().
DecryptWithSerpent()
byte [] Reina.Cryptography.Decryption.DataDecryptor.DecryptWithSerpent (byte[] encryptedBytes) inline private
Decrypts the data using the Serpent algorithm in CBC mode with PKCS7 padding.
Parameters
encryptedBytes The encrypted data with the Serpent IV prepended.
Returns
The decrypted data as a byte array.
Exceptions
ArgumentException Thrown when the encrypted data does not contain a valid Serpent IV.
Definition at line 131 of file DataDecryptor.cs.
         {
             // Initialize Serpent engine and cipher parameters.
             var serpentEngine = new SerpentEngine();
             int ivLengthSerpent = serpentEngine.GetBlockSize();
             if (encryptedBytes.Length < ivLengthSerpent)
                 throw new ArgumentException("The decrypted data is too short to contain the Serpent IV.");
             // Extract the IV from the beginning of the encrypted data.
             var ivSerpent = new byte[ivLengthSerpent];
             Array.Copy(encryptedBytes, ivSerpent, ivLengthSerpent);
             var serpentCipher = new PaddedBufferedBlockCipher(new CbcBlockCipher(serpentEngine), new Pkcs7Padding());
             var serpentKeyParam = new KeyParameter(_serpentKey);
             var serpentKeyWithIv = new ParametersWithIV(serpentKeyParam, ivSerpent);
             serpentCipher.Init(false, serpentKeyWithIv);
             // Decrypt the remaining encrypted data after the IV.
             var serpentInput = new byte[encryptedBytes.Length - ivLengthSerpent];
             Array.Copy(encryptedBytes, ivLengthSerpent, serpentInput, 0, serpentInput.Length);
             return ProcessCipher(serpentCipher, serpentInput);
         }
References Reina.Cryptography.Decryption.DataDecryptor._serpentKey, and Reina.Cryptography.Decryption.DataDecryptor.ProcessCipher().
Referenced by Reina.Cryptography.Decryption.DataDecryptor.Decrypt().
DecryptWithTwofish()
byte [] Reina.Cryptography.Decryption.DataDecryptor.DecryptWithTwofish (byte[] encryptedBytes) inline private
Decrypts the data using the Twofish algorithm in CBC mode with PKCS7 padding.
Parameters
encryptedBytes The encrypted data with the Twofish IV prepended.
Returns
The decrypted data as a byte array.
Exceptions
ArgumentException Thrown when the encrypted data does not contain a valid Twofish IV.
Definition at line 161 of file DataDecryptor.cs.
         {
             // Initialize Twofish engine and cipher parameters.
             var twofishEngine = new TwofishEngine();
             int ivLengthTwofish = twofishEngine.GetBlockSize();
             if (encryptedBytes.Length < ivLengthTwofish)
                 throw new ArgumentException("The decrypted data is too short to contain the Twofish IV.");
             // Extract the IV from the beginning of the encrypted data.
             var ivTwofish = new byte[ivLengthTwofish];
             Array.Copy(encryptedBytes, ivTwofish, ivLengthTwofish);
             var twofishCipher = new PaddedBufferedBlockCipher(new CbcBlockCipher(twofishEngine), new Pkcs7Padding());
             var keyParam = new KeyParameter(_twofishKey);
             var keyWithIv = new ParametersWithIV(keyParam, ivTwofish);
             twofishCipher.Init(false, keyWithIv);
             // Decrypt the remaining encrypted data after the IV.
             var twofishInput = new byte[encryptedBytes.Length - ivLengthTwofish];
             Array.Copy(encryptedBytes, ivLengthTwofish, twofishInput, 0, twofishInput.Length);
             return ProcessCipher(twofishCipher, twofishInput);
         }
References Reina.Cryptography.Decryption.DataDecryptor._twofishKey, and Reina.Cryptography.Decryption.DataDecryptor.ProcessCipher().
Referenced by Reina.Cryptography.Decryption.DataDecryptor.Decrypt().
ProcessCipher()
byte [] Reina.Cryptography.Decryption.DataDecryptor.ProcessCipher (IBufferedCipher cipher, byte[] input) inline private
Processes the cipher operation (decryption) on the given input data.
Parameters
cipher The cipher to use for decryption.
input The input data to decrypt.
Returns
The decrypted data as a byte array.
Definition at line 191 of file DataDecryptor.cs.
         {
             // Calculate the size of the output buffer and perform the decryption.
             var output = new byte[cipher.GetOutputSize(input.Length)];
             var len = cipher.ProcessBytes(input, 0, input.Length, output, 0);
             len += cipher.DoFinal(output, len);
             // Trim the output to the actual length of the decrypted data.
             var decrypted = new byte[len];
             Array.Copy(output, decrypted, len);
             return decrypted;
         }
Referenced by Reina.Cryptography.Decryption.DataDecryptor.DecryptWithSerpent(), and Reina.Cryptography.Decryption.DataDecryptor.DecryptWithTwofish().
ValidateKey()
void Reina.Cryptography.Decryption.DataDecryptor.ValidateKey (byte[] key, string whichKey) inline private
Validates the length of the provided cryptographic key.
Parameters
key The cryptographic key to validate.
whichKey The name of the key for error messaging purposes.
Exceptions
ArgumentException Thrown when the key is not 256 bits in length.
Definition at line 49 of file DataDecryptor.cs.
         {
             if (key.Length != 32)
                 throw new ArgumentException("Invalid key size. Expected a 256-bit key.", whichKey);
         }
Referenced by Reina.Cryptography.Decryption.DataDecryptor.DataDecryptor().
Member Data Documentation
_aesKey
readonly byte [] Reina.Cryptography.Decryption.DataDecryptor._aesKey private
Definition at line 22 of file DataDecryptor.cs.
Referenced by Reina.Cryptography.Decryption.DataDecryptor.DataDecryptor(), and Reina.Cryptography.Decryption.DataDecryptor.DecryptWithAES().
_serpentKey
readonly byte [] Reina.Cryptography.Decryption.DataDecryptor._serpentKey private
Definition at line 21 of file DataDecryptor.cs.
Referenced by Reina.Cryptography.Decryption.DataDecryptor.DataDecryptor(), and Reina.Cryptography.Decryption.DataDecryptor.DecryptWithSerpent().
_twofishKey
readonly byte [] Reina.Cryptography.Decryption.DataDecryptor._twofishKey private
Definition at line 20 of file DataDecryptor.cs.
Referenced by Reina.Cryptography.Decryption.DataDecryptor.DataDecryptor(), and Reina.Cryptography.Decryption.DataDecryptor.DecryptWithTwofish().
The documentation for this class was generated from the following file:
Decryption/DataDecryptor.cs