Reina.Cryptography: Reina.Cryptography.Library Class Reference
Reina.Cryptography.Library Class Reference
Provides core functionality for encryption and decryption of data, interfacing with Azure Key Vault for key management.
Static Public Member Functions
static void Configuration (string azureKeyVaultUrl, string azureClientId, string azureClientSecret, string azureTenantId)
Configures the library with custom Azure Key Vault settings. If this method is not called, default configuration values are used.
static string Encrypt (string decryptedString, string twofishKeyName, string serpentKeyName, string aesKeyName)
Encrypts a plaintext string using three distinct keys for Twofish, Serpent, and AES encryption algorithms.
static string Encrypt (string decryptedString, string keyName)
Encrypts a plaintext string synchronously using a specified key retrieved asynchronously from Azure Key Vault. The encryption process is a multi-layered approach that ensures data confidentiality.
static string Decrypt (string encryptedString, string twofishKeyName, string serpentKeyName, string aesKeyName)
Decrypts a Base64-encoded string using three distinct keys for Twofish, Serpent, and AES encryption algorithms.
static string Decrypt (string encryptedString, string keyName)
Decrypts a Base64-encoded string synchronously using a specified key retrieved asynchronously from Azure Key Vault. The decryption process reverses the multi-layered encryption to restore the original plaintext.
Static Private Member Functions
static void ValidateInput (string input, params string[] keyNames)
Validates the input string and key names, ensuring they are not null or empty and adhere to the expected format.
Detailed Description
Provides core functionality for encryption and decryption of data, interfacing with Azure Key Vault for key management.
Definition at line 15 of file Library.cs.
Member Function Documentation
Configuration()
static void Reina.Cryptography.Library.Configuration (string azureKeyVaultUrl, string azureClientId, string azureClientSecret, string azureTenantId) inline static
Configures the library with custom Azure Key Vault settings. If this method is not called, default configuration values are used.
Parameters
azureKeyVaultUrl Azure Key Vault URL.
azureClientId Azure client ID for authentication.
azureClientSecret Azure client secret for authentication.
azureTenantId Azure tenant ID for authentication.
Definition at line 25 of file Library.cs.
         {
             Config.Instance.SetConfiguration(azureKeyVaultUrl, azureClientId, azureClientSecret, azureTenantId);
         }
References Reina.Cryptography.Configuration.Config.Instance, and Reina.Cryptography.Configuration.Config.SetConfiguration().
Decrypt() [1/2]
static string Reina.Cryptography.Library.Decrypt (string encryptedString, string keyName) inline static
Decrypts a Base64-encoded string synchronously using a specified key retrieved asynchronously from Azure Key Vault. The decryption process reverses the multi-layered encryption to restore the original plaintext.
Parameters
encryptedString The Base64-encoded string to be decrypted.
keyName The name of the key to use for decryption.
Returns
The decrypted plaintext string.
Exceptions
ArgumentNullException Thrown if the encrypted string or key name is null or empty.
ArgumentException Thrown if the key name does not adhere to the expected format.
Definition at line 115 of file Library.cs.
         {
             return Decrypt(encryptedString, keyName, keyName, keyName);
         }
References Reina.Cryptography.Library.Decrypt().
Decrypt() [2/2]
static string Reina.Cryptography.Library.Decrypt (string encryptedString, string twofishKeyName, string serpentKeyName, string aesKeyName) inline static
Decrypts a Base64-encoded string using three distinct keys for Twofish, Serpent, and AES encryption algorithms.
Parameters
encryptedString The Base64-encoded string to be decrypted.
twofishKeyName The name of the Twofish key.
serpentKeyName The name of the Serpent key.
aesKeyName The name of the AES key.
Returns
The decrypted plaintext string.
Exceptions
ArgumentNullException Thrown if the encrypted string or any key name is null or empty.
ArgumentException Thrown if any key name does not adhere to the expected format.
Definition at line 85 of file Library.cs.
         {
             // Validate input parameters.
             ValidateInput(encryptedString, twofishKeyName, serpentKeyName, aesKeyName);
             // Retrieve the decryption keys from the Azure Key Vault.
             byte[] twofishKey = AzureKVKeyManager.Instance.GetEncryptionKeyAsync(twofishKeyName).GetAwaiter().GetResult();
             byte[] serpentKey = AzureKVKeyManager.Instance.GetEncryptionKeyAsync(serpentKeyName).GetAwaiter().GetResult();
             byte[] aesKey = AzureKVKeyManager.Instance.GetEncryptionKeyAsync(aesKeyName).GetAwaiter().GetResult();
             // Initialize the decryptor with the retrieved keys.
             var dataDecryptor = new DataDecryptor(twofishKey, serpentKey, aesKey);
             // Convert the Base64 encoded string to a byte array.
             byte[] encryptedBytes = Convert.FromBase64String(encryptedString);
             // Decrypt the data.
             byte[] decryptedBytes = dataDecryptor.Decrypt(encryptedBytes);
             // Return the decrypted data as a plaintext string.
             return Encoding.UTF8.GetString(decryptedBytes);
         }
References Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetEncryptionKeyAsync(), Reina.Cryptography.KeyManagement.AzureKVKeyManager.Instance, and Reina.Cryptography.Library.ValidateInput().
Referenced by Reina.Cryptography.Library.Decrypt().
Encrypt() [1/2]
static string Reina.Cryptography.Library.Encrypt (string decryptedString, string keyName) inline static
Encrypts a plaintext string synchronously using a specified key retrieved asynchronously from Azure Key Vault. The encryption process is a multi-layered approach that ensures data confidentiality.
Parameters
decryptedString The plaintext string to be encrypted.
keyName The name of the key to use for encryption.
Returns
A Base64-encoded string that represents the encrypted data.
Exceptions
ArgumentNullException Thrown if the input string or key name is null or empty.
ArgumentException Thrown if the key name does not adhere to the expected format.
Definition at line 70 of file Library.cs.
         {
             return Encrypt(decryptedString, keyName, keyName, keyName);
         }
References Reina.Cryptography.Library.Encrypt().
Encrypt() [2/2]
static string Reina.Cryptography.Library.Encrypt (string decryptedString, string twofishKeyName, string serpentKeyName, string aesKeyName) inline static
Encrypts a plaintext string using three distinct keys for Twofish, Serpent, and AES encryption algorithms.
Parameters
decryptedString The plaintext string to be encrypted.
twofishKeyName The name of the Twofish key.
serpentKeyName The name of the Serpent key.
aesKeyName The name of the AES key.
Returns
A Base64-encoded string representing the encrypted data.
Exceptions
ArgumentNullException Thrown if the input string or any key name is null or empty.
ArgumentException Thrown if any key name does not adhere to the expected format.
Definition at line 40 of file Library.cs.
         {
             // Input validation
             ValidateInput(decryptedString, twofishKeyName, serpentKeyName, aesKeyName);
             // Retrieve the encryption keys from the Azure Key Vault.
             byte[] twofishKey = AzureKVKeyManager.Instance.GetEncryptionKeyAsync(twofishKeyName).GetAwaiter().GetResult();
             byte[] serpentKey = AzureKVKeyManager.Instance.GetEncryptionKeyAsync(serpentKeyName).GetAwaiter().GetResult();
             byte[] aesKey = AzureKVKeyManager.Instance.GetEncryptionKeyAsync(aesKeyName).GetAwaiter().GetResult();
             // Initialize the encryptor with the retrieved key.
             var dataEncryptor = new DataEncryptor(twofishKey, serpentKey, aesKey);
             // Convert the plaintext string to a byte array.
             byte[] decryptedBytes = Encoding.UTF8.GetBytes(decryptedString);
             // Encrypt the data.
             byte[] encryptedBytes = dataEncryptor.Encrypt(decryptedBytes);
             // Return the encrypted data as a Base64 encoded string.
             return Convert.ToBase64String(encryptedBytes);
         }
References Reina.Cryptography.KeyManagement.AzureKVKeyManager.GetEncryptionKeyAsync(), Reina.Cryptography.KeyManagement.AzureKVKeyManager.Instance, and Reina.Cryptography.Library.ValidateInput().
Referenced by Reina.Cryptography.Library.Encrypt().
ValidateInput()
static void Reina.Cryptography.Library.ValidateInput (string input, params string[] keyNames) inline static private
Validates the input string and key names, ensuring they are not null or empty and adhere to the expected format.
Parameters
input The input string to validate.
keyNames The key names to validate.
Exceptions
ArgumentNullException Thrown if the input or any key name is null or empty.
ArgumentException Thrown if any key name does not match the required pattern.
Definition at line 127 of file Library.cs.
         {
             // Validate that the input string is not null or empty.
             if (string.IsNullOrEmpty(input))
                 throw new ArgumentNullException(nameof(input), "Input cannot be null or empty.");
             // Validate the format of each key name.
             foreach (var keyName in keyNames)
             {
                 if (string.IsNullOrEmpty(keyName))
                     throw new ArgumentNullException(nameof(keyName), "Key name cannot be null or empty.");
                 if (!System.Text.RegularExpressions.Regex.IsMatch(keyName, @"^[a-zA-Z][a-zA-Z0-9\-]{0,126}$"))
                     throw new ArgumentException("Invalid key name. A key name can be 1-127 characters, starting with a letter, containing only 0-9, a-z, A-Z, and -", nameof(keyName));
             }
         }
Referenced by Reina.Cryptography.Library.Decrypt(), and Reina.Cryptography.Library.Encrypt().
The documentation for this class was generated from the following file:
Library.cs