Reina.Cryptography: Reina.Cryptography.Encryption.DataEncryptor Class Reference
Reina.Cryptography.Encryption.DataEncryptor Class Reference
Implements encryption operations using a cascading triple-layered technique with Twofish, Serpent, and AES algorithms. This class provides a high level of security by encrypting data in multiple stages.
Public Member Functions
DataEncryptor (byte[] twofishKey, byte[] serpentKey, byte[] aesKey)
Initializes a new instance of the DataEncryptor class with the specified keys for Twofish, Serpent, and AES.
byte[] Encrypt (byte[] decryptedBytes)
Encrypts the specified plaintext data using a layered approach with Twofish, Serpent, and AES algorithms.
Private Member Functions
void ValidateKey (byte[] key, string whichKey)
Validates the length of the provided cryptographic key.
byte[] EncryptWithTwofish (byte[] data)
Encrypts the data using the Twofish algorithm in CBC mode with PKCS7 padding.
byte[] EncryptWithSerpent (byte[] data)
Encrypts the data using the Serpent algorithm in CBC mode with PKCS7 padding.
byte[] EncryptWithAES (byte[] data)
Encrypts the data using the AES algorithm in its default mode with an auto-generated IV.
Private Attributes
readonly byte[] _twofishKey
readonly byte[] _serpentKey
readonly byte[] _aesKey
Detailed Description
Implements encryption operations using a cascading triple-layered technique with Twofish, Serpent, and AES algorithms. This class provides a high level of security by encrypting data in multiple stages.
Definition at line 18 of file DataEncryptor.cs.
Constructor & Destructor Documentation
DataEncryptor()
Reina.Cryptography.Encryption.DataEncryptor.DataEncryptor (byte[] twofishKey, byte[] serpentKey, byte[] aesKey) inline
Initializes a new instance of the DataEncryptor class with the specified keys for Twofish, Serpent, and AES.
Parameters
twofishKey The 256-bit Twofish key for encryption.
serpentKey The 256-bit Serpent key for encryption.
aesKey The 256-bit AES key for encryption.
Exceptions
ArgumentNullException Thrown when any key is null.
ArgumentException Thrown when any key is not 256 bits in length.
Definition at line 32 of file DataEncryptor.cs.
         {
             _twofishKey = twofishKey ?? throw new ArgumentNullException(nameof(twofishKey), "Twofish key cannot be null.");
             _serpentKey = serpentKey ?? throw new ArgumentNullException(nameof(serpentKey), "Serpent key cannot be null.");
             _aesKey = aesKey ?? throw new ArgumentNullException(nameof(aesKey), "AES key cannot be null.");
             ValidateKey(_twofishKey, nameof(twofishKey));
             ValidateKey(_serpentKey, nameof(serpentKey));
             ValidateKey(_aesKey, nameof(aesKey));
         }
References Reina.Cryptography.Encryption.DataEncryptor._aesKey, Reina.Cryptography.Encryption.DataEncryptor._serpentKey, Reina.Cryptography.Encryption.DataEncryptor._twofishKey, and Reina.Cryptography.Encryption.DataEncryptor.ValidateKey().
Member Function Documentation
Encrypt()
byte [] Reina.Cryptography.Encryption.DataEncryptor.Encrypt (byte[] decryptedBytes) inline
Encrypts the specified plaintext data using a layered approach with Twofish, Serpent, and AES algorithms.
Parameters
decryptedBytes The plaintext data to encrypt.
Returns
The encrypted data as a byte array, including the initialization vectors (IVs) for each encryption stage.
Exceptions
ArgumentNullException Thrown when the plaintext data is null.
Implements Reina.Cryptography.Interfaces.IEncryptor.
Definition at line 61 of file DataEncryptor.cs.
         {
             if (decryptedBytes == null)
                 throw new ArgumentNullException(nameof(decryptedBytes), "Plaintext data to encrypt cannot be null.");
             // Perform encryption in the order of Twofish, Serpent, and then AES.
             var twofishEncrypted = EncryptWithTwofish(decryptedBytes);
             var serpentEncrypted = EncryptWithSerpent(twofishEncrypted);
             var aesEncrypted = EncryptWithAES(serpentEncrypted);
             return aesEncrypted;
         }
References Reina.Cryptography.Encryption.DataEncryptor.EncryptWithAES(), Reina.Cryptography.Encryption.DataEncryptor.EncryptWithSerpent(), and Reina.Cryptography.Encryption.DataEncryptor.EncryptWithTwofish().
EncryptWithAES()
byte [] Reina.Cryptography.Encryption.DataEncryptor.EncryptWithAES (byte[] data) inline private
Encrypts the data using the AES algorithm in its default mode with an auto-generated IV.
Parameters
data The data to encrypt, typically already encrypted by other algorithms.
Returns
The encrypted data as a byte array, including the initialization vector (IV).
Definition at line 141 of file DataEncryptor.cs.
         {
             // Initialize AES engine.
             using var aes = Aes.Create();
             aes.Key = _aesKey;
             aes.GenerateIV();
             // Perform encryption, writing the IV followed by the encrypted data.
             using var memoryStream = new MemoryStream();
             memoryStream.Write(aes.IV, 0, aes.IV.Length);
             using var cryptoStream = new CryptoStream(memoryStream, aes.CreateEncryptor(), CryptoStreamMode.Write);
             cryptoStream.Write(data, 0, data.Length);
             cryptoStream.FlushFinalBlock();
             return memoryStream.ToArray();
         }
References Reina.Cryptography.Encryption.DataEncryptor._aesKey.
Referenced by Reina.Cryptography.Encryption.DataEncryptor.Encrypt().
EncryptWithSerpent()
byte [] Reina.Cryptography.Encryption.DataEncryptor.EncryptWithSerpent (byte[] data) inline private
Encrypts the data using the Serpent algorithm in CBC mode with PKCS7 padding.
Parameters
data The data to encrypt, typically already encrypted by another algorithm.
Returns
The encrypted data as a byte array, including the initialization vector (IV).
Definition at line 110 of file DataEncryptor.cs.
         {
             // Initialize Serpent engine and cipher parameters.
             var serpentEngine = new SerpentEngine();
             var serpentBlockCipher = new CbcBlockCipher(serpentEngine);
             var serpentCipher = new PaddedBufferedBlockCipher(serpentBlockCipher, new Pkcs7Padding());
             var serpentKeyParam = new KeyParameter(_serpentKey);
             var serpentRandom = new SecureRandom();
             var ivSerpent = new byte[serpentEngine.GetBlockSize()];
             serpentRandom.NextBytes(ivSerpent);
             var serpentKeyWithIv = new ParametersWithIV(serpentKeyParam, ivSerpent);
             serpentCipher.Init(true, serpentKeyWithIv);
             // Perform encryption.
             var serpentOutput = new byte[serpentCipher.GetOutputSize(data.Length)];
             var serpentLen = serpentCipher.ProcessBytes(data, 0, data.Length, serpentOutput, 0);
             serpentCipher.DoFinal(serpentOutput, serpentLen);
             // Prepend IV to the encrypted data.
             var serpentEncrypted = new byte[ivSerpent.Length + serpentOutput.Length];
             Array.Copy(ivSerpent, 0, serpentEncrypted, 0, ivSerpent.Length);
             Array.Copy(serpentOutput, 0, serpentEncrypted, ivSerpent.Length, serpentOutput.Length);
             return serpentEncrypted;
         }
References Reina.Cryptography.Encryption.DataEncryptor._serpentKey.
Referenced by Reina.Cryptography.Encryption.DataEncryptor.Encrypt().
EncryptWithTwofish()
byte [] Reina.Cryptography.Encryption.DataEncryptor.EncryptWithTwofish (byte[] data) inline private
Encrypts the data using the Twofish algorithm in CBC mode with PKCS7 padding.
Parameters
data The plaintext data to encrypt.
Returns
The encrypted data as a byte array, including the initialization vector (IV).
Definition at line 79 of file DataEncryptor.cs.
         {
             // Initialize Twofish engine and cipher parameters.
             var twofishEngine = new TwofishEngine();
             var blockCipher = new CbcBlockCipher(twofishEngine);
             var cipher = new PaddedBufferedBlockCipher(blockCipher, new Pkcs7Padding());
             var keyParam = new KeyParameter(_twofishKey);
             var random = new SecureRandom();
             var ivTwofish = new byte[twofishEngine.GetBlockSize()];
             random.NextBytes(ivTwofish);
             var keyWithIv = new ParametersWithIV(keyParam, ivTwofish);
             cipher.Init(true, keyWithIv);
             // Perform encryption.
             var output = new byte[cipher.GetOutputSize(data.Length)];
             var len = cipher.ProcessBytes(data, 0, data.Length, output, 0);
             cipher.DoFinal(output, len);
             // Prepend IV to the encrypted data.
             var twofishEncrypted = new byte[ivTwofish.Length + output.Length];
             Array.Copy(ivTwofish, 0, twofishEncrypted, 0, ivTwofish.Length);
             Array.Copy(output, 0, twofishEncrypted, ivTwofish.Length, output.Length);
             return twofishEncrypted;
         }
References Reina.Cryptography.Encryption.DataEncryptor._twofishKey.
Referenced by Reina.Cryptography.Encryption.DataEncryptor.Encrypt().
ValidateKey()
void Reina.Cryptography.Encryption.DataEncryptor.ValidateKey (byte[] key, string whichKey) inline private
Validates the length of the provided cryptographic key.
Parameters
key The cryptographic key to validate.
whichKey The name of the key for error messaging purposes.
Exceptions
ArgumentException Thrown when the key is not 256 bits in length.
Definition at line 49 of file DataEncryptor.cs.
         {
             if (key.Length != 32)
                 throw new ArgumentException("Invalid key size. Expected a 256-bit key.", whichKey);
         }
Referenced by Reina.Cryptography.Encryption.DataEncryptor.DataEncryptor().
Member Data Documentation
_aesKey
readonly byte [] Reina.Cryptography.Encryption.DataEncryptor._aesKey private
Definition at line 22 of file DataEncryptor.cs.
Referenced by Reina.Cryptography.Encryption.DataEncryptor.DataEncryptor(), and Reina.Cryptography.Encryption.DataEncryptor.EncryptWithAES().
_serpentKey
readonly byte [] Reina.Cryptography.Encryption.DataEncryptor._serpentKey private
Definition at line 21 of file DataEncryptor.cs.
Referenced by Reina.Cryptography.Encryption.DataEncryptor.DataEncryptor(), and Reina.Cryptography.Encryption.DataEncryptor.EncryptWithSerpent().
_twofishKey
readonly byte [] Reina.Cryptography.Encryption.DataEncryptor._twofishKey private
Definition at line 20 of file DataEncryptor.cs.
Referenced by Reina.Cryptography.Encryption.DataEncryptor.DataEncryptor(), and Reina.Cryptography.Encryption.DataEncryptor.EncryptWithTwofish().
The documentation for this class was generated from the following file:
Encryption/DataEncryptor.cs