name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "Resources/"

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      # Checks-out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Calculate version number
      - name: Calculate version
        id: version
        run: |
          # Fetch current version from csproj
          [xml]$csproj = Get-Content "Reina.Cryptography.csproj"
          $currentVersion = $csproj.Project.PropertyGroup.Version
          $versionParts = $currentVersion.Split('.')
          $major = [int]$versionParts[0]
          $minor = [int]$versionParts[1]
          $build = [int]$versionParts[2]

          # Calculate new version
          $commitCount = git rev-list --count HEAD
          $build = ($build + $commitCount) % 10
          if ($build -eq 0 -and $commitCount -ne 0) {
            $minor += 1
            if ($minor -eq 10) {
              $major += 1
              $minor = 0
            }
          }
          $newVersion = "$major.$minor.$build"
          echo "New version: $newVersion"
          echo "::set-output name=version::$newVersion"

      # Update .csproj file
      - name: Update project version
        run: |
          $csprojPath = "Reina.Cryptography.csproj"
          [xml]$csproj = Get-Content $csprojPath
          $csproj.Project.PropertyGroup.Version = "${{ steps.version.outputs.version }}"
          $csproj.Save($csprojPath)
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $csprojPath
          git commit -m "Update version to ${{ steps.version.outputs.version }}"
          git push

      # Install dependencies and build for both target frameworks
      - name: Build Project for .NET Framework 4.8.1 and .NET 7
        run: |
          dotnet restore Reina.Cryptography.csproj
          dotnet build Reina.Cryptography.csproj --configuration Release

      # List build output for debugging purposes
      - name: List build output
        run: |
          dir .\bin\Release\

      # Create a release
      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
          title: "Latest Build v${{ steps.version.outputs.version }}"

      # Upload .dll for .NET Framework 4.8.1 as an asset to the release
      - name: Upload .NET Framework 4.8.1 DLL
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/Release/net481/Reina.Cryptography.net481.dll
          asset_name: Reina.Cryptography.net481.dll
          asset_content_type: application/octet-stream

      # Upload .dll for .NET 7 as an asset to the release
      - name: Upload .NET 7 DLL
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/Release/net7.0/Reina.Cryptography.net7.0.dll
          asset_name: Reina.Cryptography.net7.0.dll
          asset_content_type: application/octet-stream
