name: Check Dependencies

on:
  schedule:
    # This will run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: windows-latest

    steps:
      # Checks-out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Sets up .NET SDK for .NET 7.0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.13'

      # Install .NET Framework 4.8.1
      - name: Install .NET Framework 4.8.1
        run: |
          $url = "https://go.microsoft.com/fwlink/?linkid=2203306"
          $output = "dotnet-framework-installer.exe"
          $arguments = "/q /norestart"

          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList $arguments -Wait
        shell: powershell

      # Install dependencies and build project for .NET Framework 4.8.1
      - name: Install dependencies and build for .NET Framework 4.8.1
        run: |
          dotnet restore
          dotnet build --no-restore --framework net481

      # Check for updates for .NET Framework 4.8.1
      - name: Check for updates for .NET Framework 4.8.1
        run: dotnet list package --outdated --framework net481

      # Install dependencies and build project for .NET 7.0
      - name: Install dependencies and build for .NET 7.0
        run: |
          dotnet restore
          dotnet build --no-restore --framework net7.0

      # Check for updates for .NET 7.0
      - name: Check for updates for .NET 7.0
        run: dotnet list package --outdated --framework net7.0

      # If there are updates, create a pull request with the changes
      - name: Create Pull Request for updates
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update dependencies
          title: 'Dependencies Update'
          body: 'This pull request updates the following dependencies'
          branch: 'dependencies-update'
          delete-branch: true

      # Output the URL of the created pull request if any
      - name: Check output
        run: echo "Pull Request URL - ${{ steps.create_pull_request.outputs.pull-request-url }}"
