name: Check Dependencies

on:
  schedule:
    # This will run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: windows-latest

    steps:
      # Checks-out repository
      - name: Check out code
        uses: actions/checkout@v3

      # Sets up .NET Core for net7.0
      - name: Setup .NET for net7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      # Install dependencies and build project for net7.0
      - name: Install dependencies and build for net7.0
        run: |
          dotnet restore --framework net7.0
          dotnet build --no-restore --framework net7.0

      # Check for updates for net7.0
      - name: Check for updates for net7.0
        run: dotnet list package --outdated --framework net7.0

      # Install dependencies and build project for .NET Framework
      - name: Install dependencies and build for .NET Framework
        run: |
          dotnet restore --framework net48
          dotnet build --no-restore --framework net48

      # Check for updates for .NET Framework
      - name: Check for updates for .NET Framework
        run: dotnet list package --outdated --framework net48

      # If there are updates, create a pull request with the changes
      - name: Create Pull Request for updates
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update dependencies
          title: 'Dependencies Update'
          body: 'This pull request updates the following dependencies'
          branch: 'dependencies-update'
          delete-branch: true

      # Output the URL of the created pull request if any
      - name: Check output
        run: echo "Pull Request URL - ${{ steps.create_pull_request.outputs.pull-request-url }}"
